### ISSUE TITLE
Makefile is empty

### ISSUE THREAD

**Issue by rsteinfe1** [kundajelab/gecco-rna#1]
Hi,

just wanted to let you know that your Makefile is empty.

Best wishes,
Robert

**Comment by chrisprobert** [comment]
Hi Robert,

Thanks for pointing that out. I initially added the Makefile because we were going to compile STAR from source, but I decided to just use the STAR binaries (under in our source tree: `/src/STAR/bin/`). I suppose we could just delete the Makefile now.
